Repository Cemag-pcp/apontamento_v2, pull requests merged in 2025-05, with the labels that each got.

#4 Funcionalidade/desfazer processo
  apontamento_montagem/static/js/ordem-criada-montagem.js
  apontamento_montagem/templates/apontamento_montagem/planejamento.html
  apontamento_montagem/urls.py
  apontamento_montagem/views.py
  apontamento_v2/settings/dev.py
Labels: funcionalidade

#6 :sparkles: feat: Desfazer processo de apontamento em Estamparia
  apontamento_estamparia/static/js/ordem-criada-estamparia.js
  apontamento_estamparia/templates/apontamento_estamparia/planejamento.html
  apontamento_estamparia/urls.py
  apontamento_estamparia/views.py
  apontamento_v2/settings/dev.py
Labels: funcionalidade

#7 Exibindo Máquina Não identificada na inspeção de Estamparia
  apontamento_v2/settings/dev.py
  inspecao/views.py
Labels: bug

#9 Nome do Inspetor direcionado pelo Login
  inspecao/templates/inspecao_estamparia.html
  inspecao/templates/modal_inspecao/modal_inspecao_montagem.html
  inspecao/templates/modal_inspecao/modal_inspecao_pintura.html
  inspecao/templates/modal_inspecao/modal_inspecao_tanque.html
  inspecao/templates/modal_inspecao/modal_inspecao_tubos_cilindros.html
  inspecao/views.py
Labels: melhoria

#16 Modificar espessura e tipo chapa em duplicar OP
  apontamento_corte/static/js/duplicar-op.js
  apontamento_corte/views.py
  apontamento_v2/settings/dev.py
Labels: melhoria

#21 :sparkles: feat: Adicionando filtro de turno (corte)
  apontamento_corte/static/js/ordem-criada.js
  apontamento_corte/static/js/planejar-laser.js
  apontamento_corte/templates/apontamento_corte/planejamento.html
  apontamento_corte/views.py
Labels: funcionalidade

#22 :sparkles: feat: Adicionando operador pela maquina
  apontamento_montagem/static/js/ordem-criada-montagem.js
  apontamento_montagem/templates/apontamento_montagem/planejamento.html
  apontamento_montagem/views.py
  cadastro/migrations/0030_operador_maquina.py
  cadastro/models.py
Labels: melhoria

#24 Melhoria/operador maquina
  apontamento_montagem/views.py
  apontamento_v2/settings/dev.py
  cadastro/migrations/0031_remove_operador_maquina_operador_maquinas.py
  cadastro/models.py
Labels: melhoria

#31 :bug: fix: Removendo related_name da FK inspecao
  inspecao/models.py
Labels: bug

#33 :bug: fix: Selecionar Operador
  apontamento_montagem/static/js/ordem-criada-montagem.js
Labels: bug

#35 :sparkles: feat: Alerta para inspetores referente ao retrabalho e a r…
  inspecao/static/js/pintura/alerta-reinspecao.js
  inspecao/static/js/pintura/inspecionar/enviar-inspecao.js
  inspecao/static/js/pintura/reinspecionar/envio-reinspecao.js
  inspecao/templates/inspecao_pintura.html
  inspecao/urls.py
  inspecao/views.py
Labels: melhoria
